apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: realdiag-ingress
  namespace: staging
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  ingressClassName: nginx
  rules:
    - host: api.realdiag.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: realdiag-api
                port:
                  number: 80
    - host: realdiag.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: realdiag-web
                port:
                  number: 80
